sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run coverage && npm t -- --browsers=Firefox,BrowserStack_Edge,BrowserStack_Safari
env:
  global:
  - secure: ZNswdUStpHjer4LfNPhzIcsIUtv6R3wzaLIkQIhuXN+THZUwIBtPRjKU6XIBH29GoiSBsYrpjoq9m91iW9nkGhUFq+N/seeHvqDMj2eH5qmWK0jB8pPkrBBEe/70FdhncEeOhfX0KHhsFarpmmW6dcshrAvz35gp6DKuzs/a0QgV+XUnduc3OZ39yz5hQAaMfBJEaci0ZmMI52z9Q4Jf2FmljosznDQZ6ZU808vWxSZMeqknDqLcMRQ4X8okj1+7345K28X3uDetAY7EcmeBKUMJa/d/J1lzMD6DpqSwNiYRZ2FFXf8TZqZscCn4lB9SEW8YRkO1teO3stXQp+aeG7GS3o2c4nhNN4poeERmfa4c/ydSAGV+tsfzSV8Ye5pMUWfFtGvfiq8gkFNtLqL2B2N3fAhQlO5rYSx77f0mWpFGx3ys9UJCTUEExtpeK99ENSLQrgGukovxWRKZlbxDp4NxGnxK2RuSn0WmS1BUXRFxAxL0UdSkoeWDvw6me3WlfrQxEboR19BTHaMLFjJBrmbVylTHI7OsNrSFSuva/Mh2BKl3fYta2OnW2T9T79/NIsmgcDw9A9DeNwkFqdPaqCE+vgrEefly2oaUDl9nyCqu9yCkiATyVHkskniDhihSvz0FYScCYcyQ2OIUx2heMrXA1Nforhmnt7N2+3bnodE=
  - secure: H++mTZEIu0MQr1zsxHhFcJ5Kuf8rspWOEnt9GyvJmE6YIaU4+cYmWcDorqOL/q9AftHGg65Rn4quoA4WWBpSkWoMctRl1ySp2r4qz+o9D6LM1Nm+HLXMkoEyB9eYVdXkaPO2BK9DgugLMwWSx1IT4l3lY6UIXFsJhdFpBB3mT9TfNC5mRcXtknM9I+7tcfgDKx1lkhl/YCBspyXmJdC/ntN3UlBofTGwPG92XWJ2JOZFEXm3H8gpSTy8m3KWPt1lOMlfT1tZWNEHWMVduYjMZz+AKqNY9OKe/nHDRoe5GRqTLvhnlSjGyrtBtMTj3f1lwJ6bez4lONiU8qNyDIZ2IHcCDjaP5im0hyY6zsczHrOLJeTajr4eQ7NxQERGgohu33wGVvNG7zLeRByZf85PQYTx28HcQRwYfCvEBA9sifs/VddiLyjkwFrrWx/dFbIwFL2/Fiwz6wQN/FLpg5bG9crCA2JMA/5+ua3HSXZtoZkF5W7bSS9+pHfgcU2DLEid9Q/IGxg/CKmMESITAXwyA8Mwd5YZVhargHLkUMRMMtjiXi30srbXsp/ICQXMuYr/0l/nnwQISZuBGnwSHfDuqhJxok5TdHnbhXvXNWkXcIJF7Iy7BEDe73XOE9VohszTXBSIqOMEkAdgMwNsxI8CXeIh68xZURPGatcd/g9K+Yg=
